/**
		
	Do not edit this file. It's generated automatically from template/acceptance.tests.template.
		
*/
define(['../acceptance/spec/app', '../acceptance/spec/editor', '../acceptance/spec/facts', '../acceptance/spec/monitor/editor', '../acceptance/spec/monitor/info', '../acceptance/spec/monitor/navigation', '../acceptance/spec/monitor/open', '../acceptance/spec/monitor/save', '../acceptance/spec/monitor/stats', '../acceptance/spec/open', '../acceptance/spec/preview', '../acceptance/spec/save', '../acceptance/spec/settings', '../acceptance/spec/smoke', '../acceptance/spec/stats'], function() {});